### ISSUE TITLE
use on own image

### ISSUE THREAD

**Issue by ABDOELSHEMY** [WenlongZhang0724/RankSRGAN#1]
Hi @WenlongZhang0724 
thank you very much for sharing your code with us
could you please explain how to use with my own images, without using json file

**Comment by WenlongZhang0724** [comment]
Thanks for your interest in our work!
In our code framework, you can super-solve your own images by the section "How to test". You just need some simple configuration. In addition, I will give more detailed steps about our codes in the near future. By the way, Why don't you use the JSON file?

**Comment by ABDOELSHEMY** [comment]
thanks for your reply!
In fact I have tried to experiment using JSON file but Unfortunately i faild, anyway your work result look amazing, thank you
